[[main]]
none = "none"

[[main]]
name = "Projects"
pre = "lightbulb"
pageRef = "projects"
identifier = "moiu2F7xND"
weight = 9_999

[[main]]
name = "Articles"
pre = "envelope"
pageRef = "blog"
identifier = "y3yRu5JoPn"
weight = 9_999

[[main]]
name = "Contact"
pre = "email"
pageRef = "contact"
identifier = "b96SDTdp82"
weight = 9_999

[[main]]
name = "About"
pageRef = "about"
identifier = "2cpNe6j1YY"
weight = 9_999

[[footer]]
none = "none"
